# Generated by Django 3.0.7 on 2023-03-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='placedAt',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
