# Generated by Django 3.0.7 on 2023-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_placedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='desc',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
