# Generated by Django 3.0.7 on 2023-03-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
