# Generated by Django 3.0.7 on 2023-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='img',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
