# Generated by Django 3.0.7 on 2023-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='audited',
            field=models.BooleanField(default=False),
        ),
    ]
