# Generated by Django 3.0.7 on 2023-12-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock_audited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='description_of_item',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='desc',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='placedAt',
            new_name='po',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='img',
        ),
        migrations.AddField(
            model_name='stock',
            name='registration',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='remarks',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
