# Generated by Django 3.0.7 on 2023-12-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20231218_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='read',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_of_item', models.CharField(max_length=30, unique=True)),
                ('po', models.CharField(default='unknown', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('location', models.CharField(default='none', max_length=200)),
                ('registration', models.CharField(default='none', max_length=200)),
                ('status', models.CharField(default='none', max_length=200)),
                ('remarks', models.CharField(default='none', max_length=200)),
                ('qrcode', models.ImageField(blank=True, upload_to='qr_codes')),
                ('is_deleted', models.BooleanField(default=False)),
                ('audited', models.BooleanField(default=False)),
            ],
        ),
    ]
