# Generated by Django 3.0.7 on 2023-12-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='read',
        ),
    ]
