# Generated by Django 3.0.7 on 2023-11-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='stock',
        ),
        migrations.DeleteModel(
            name='PurchaseBill',
        ),
        migrations.DeleteModel(
            name='PurchaseBillDetails',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='SaleBill',
        ),
        migrations.DeleteModel(
            name='SaleBillDetails',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
